### ISSUE TITLE
Battery level value is broken?

### ISSUE THREAD

**Issue by ANS-spb** [joshpirihi/meshtastic-mqtt#12]
The battery_level field in the URL for Traccar is always 0, even if the actual battery level, visible in nodes table, is 100% or another.

![image](https://user-images.githubusercontent.com/72073134/154213479-9e453fff-ca4c-4e7b-be92-51f5add3c2e6.png)

![image](https://user-images.githubusercontent.com/72073134/154213590-6c9dcec3-aa1d-4d2e-9ec4-416675c39bc5.png)

![image](https://user-images.githubusercontent.com/72073134/154213790-ef07af90-08f6-4c30-8f53-22f0c88269ad.png)

**Comment by joshpirihi** [comment]
Hey!  Good to see you're using the script!

I'd make sure you're including battery level in the position flags of the transmitting node.  It doesn't look like that's in the position packet

**Comment by ANS-spb** [comment]
![image](https://user-images.githubusercontent.com/72073134/154897094-2e304229-f81c-4169-b1c9-c10fa39ce702.png)
I'm sorry, reallysome nodes did not report their battery levels.
I jumped to conclusions, my apologies :)

All is working correctly
